#!/bin/sh
set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Remove multiflexi-cli data from /var/lib/composer to free space after package removal.
        if [ -d "/var/lib/composer/multiflexi-cli/" ]; then
            rm -rf /var/lib/composer/multiflexi-cli/
        fi
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
