<?php

namespace Test\MultiFlexi\Cli\Command;

use MultiFlexi\Cli\Command\CompanyAppCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-29 at 12:54:08.
 */
class CompanyAppCommandTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var CompanyAppCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new CompanyAppCommand();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }
}
