<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Cli\Command;

use MultiFlexi\Cli\Command\CompanyAppCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-29 at 12:54:08.
 */
class CompanyAppCommandTest extends \PHPUnit\Framework\TestCase
{
    protected CompanyAppCommand $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new CompanyAppCommand();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }

    /**
     * Test that the command defines standard pagination options.
     */
    public function testPaginationOptionsAreDefined(): void
    {
        $definition = $this->object->getDefinition();
        $this->assertTrue($definition->hasOption('limit'), 'Missing --limit option');
        $this->assertTrue($definition->hasOption('order'), 'Missing --order option');
    }
}
