<?php

namespace Test\MultiFlexi\Cli\Command;

use MultiFlexi\Cli\Command\JobCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-29 at 12:54:08.
 */
class JobCommandTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var JobCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new JobCommand();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers MultiFlexi\Cli\Command\JobCommand::listing
     * @todo   Implement testlisting().
     */
    public function testlisting() {
        $this->assertEquals('', $this->object->listing());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
