<?php

namespace Test\MultiFlexi\Cli\Command;

use MultiFlexi\Cli\Command\MultiFlexiCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-29 at 12:54:08.
 */
class MultiFlexiCommandTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var MultiFlexiCommand
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void {
        $this->object = new MultiFlexiCommand();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void {
        
    }

    /**
     * @covers MultiFlexi\Cli\Command\MultiFlexiCommand::listing
     * @todo   Implement testlisting().
     */
    public function testlisting() {
        $this->assertEquals('', $this->object->listing());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Cli\Command\MultiFlexiCommand::outputTable
     * @todo   Implement testoutputTable().
     */
    public function testoutputTable() {
        $this->assertEquals('', $this->object->outputTable());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers MultiFlexi\Cli\Command\MultiFlexiCommand::outputResult
     * @todo   Implement testoutputResult().
     */
    public function testoutputResult() {
        $this->assertEquals('', $this->object->outputResult());
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete('This test has not been implemented yet.');
    }
}
