<?php

declare(strict_types=1);

/**
 * This file is part of the MultiFlexi package
 *
 * https://multiflexi.eu/
 *
 * (c) Vítězslav Dvořák <http://vitexsoftware.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Test\MultiFlexi\Cli\Command;

use MultiFlexi\Cli\Command\RunTemplateCommand;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2025-07-29 at 12:54:07.
 */
class RunTemplateCommandTest extends \PHPUnit\Framework\TestCase
{
    protected RunTemplateCommand $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new RunTemplateCommand();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
    }
}
